### ISSUE TITLE
Zpětná vazba

### ISSUE THREAD

**Issue by ifischerova** [Klatnik/PROJEKT-Cukrarna#1]
Ahoj Kačko, 

vypadá to dost dobře 👍 

Co je třeba opravit:
- velikost loga má být 170px
- texty v `menu` nemají nastylované písmo, měla by tam být `Lora`
- hero banner nemá horní a dolní padding 80px
- text a h1 v hero sekci nejsou odsazené 40% zprava
- nadpis h2 v sekci Přístup a h3 nejsou obarveny 
- pozor na to, že zápis `<div class="produkt dva">` se bude interpretovat tak, ze ten div ma dve tridy, tridu "produkt" a tridu "dva".

Tipy:
- odkazům bych přidala i pseudotřídu `:focus`
- Horní a dolní padding můžeš zapsat i jako jednu vlastnost `padding: 80px 0;` .
- Kdybys i z hero banneru udělala section, tak bys pak mohla napsat třeba
```
section {
  padding: 80px 0;
}
```
 a ušetříš si to psát u každé sekce zvlášť. Když to pak chceš měnit, změníš to jen na jednom místě. 
To by šlo např i u těch nadpisů, dát např. `h2` a `h3` stejnou barvu v rámci vícenásobného selektoru a předejdeš tak tomu, že ve třetí sekci už na ten třetí nadpis h2 v dokumentu zapomeneš. 

- Není třeba vždy všem tagům davat classy - např. nadpisy bych stylovala přímo jako tagy. Zrovna třeba `h1` by měl být na stránce vždy jen jeden, takže tam se ani nemusíš bát toho, že by sis to nějak později přepsala. 
- Pokud bys chtěla dávat classy všude, tak by jejich název měl odrážet to, co dělají nebo co popisují...a to např.classa "poteseni", ktera styluje h1, úplně neni ten případ :)
- Abys nemusela centrování a šířku obsahu řešit u každé sekce, šlo by udělat jednu class, kam přidáš patřičné vlastnosti a tuto class pak přidáš k odpovídajícím elementům.
- Ve víceslovných názvech tříd je lepší slova oddělovat pomlčkami ;)

**Comment by Klatnik** [comment]
Ahoj, opravila jsem chyby, ale pořád nemůžu přijít na to, jak mám ten text v sekci hero odsadit o těch 40 % :)

**Comment by ifischerova** [comment]
Ahoj, u sebe jsem to vyřešila tak, že jsem si danou část s texty obalila divem a pak mu nastavila šířku 60% :) 

https://github.com/ifischerova/PROJEKT-Cukrarna/blob/main/style.css

**Comment by Klatnik** [comment]
Díky, opraveno.

**Comment by ifischerova** [comment]
Ahoj, bezva 👍
